import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ContainerData, BOX_DARK_BLUE } from '../types';

export function generatePDF(container: ContainerData): jsPDF {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 61, 128); // BOX_DARK_BLUE
  doc.text('Container Loading/Unloading Report', 20, 20);
  
  // Container Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Container #: ${container.containerNumber}`, 20, 35);
  doc.text(`Operation Type: ${container.operationType}`, 20, 42);
  doc.text(`Door #: ${container.doorNumber}`, 20, 49);
  doc.text(`Date: ${new Date(container.updatedAt).toLocaleDateString()}`, 20, 56);
  doc.text(`Time: ${new Date(container.updatedAt).toLocaleTimeString()}`, 20, 63);
  
  // Piece Count Table
  const pieceData = container.pieceCount.map(item => [item.type, item.quantity.toString()]);
  autoTable(doc, {
    startY: 72,
    head: [['Package Type', 'Quantity']],
    body: pieceData,
    theme: 'grid',
    headStyles: { fillColor: [0, 97, 213] },
  });
  
  // Materials Supplied
  const lastY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.text('Materials Supplied:', 20, lastY);
  doc.setFontSize(10);
  const materialsList = Object.entries(container.materials)
    .filter(([_, qty]) => qty > 0)
    .map(([name, qty]) => `${name}: ${qty}`)
    .join(', ') || 'None';
  doc.text(materialsList, 20, lastY + 7);
  
  // Discrepancies
  doc.setFontSize(12);
  doc.text('Discrepancies:', 20, lastY + 20);
  doc.setFontSize(10);
  const discText = container.discrepancies || 'None reported';
  const splitDisc = doc.splitTextToSize(discText, 170);
  doc.text(splitDisc, 20, lastY + 27);
  
  // Photos
  if (container.photos.length > 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.text(`Photos (${container.photos.length} total)`, 20, 20);
    
    let yPos = 30;
    container.photos.forEach((photo, index) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      try {
        doc.addImage(photo.src, 'JPEG', 20, yPos, 170, 100);
        doc.setFontSize(10);
        doc.text(`Photo ${index + 1}`, 20, yPos + 105);
        yPos += 115;
      } catch (error) {
        console.error('Error adding image to PDF:', error);
      }
    });
  }
  
  // Footer on first page
  doc.setPage(1);
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Warehouse Manager', 20, 285);
  doc.text(`Report ID: ${container.id}`, 20, 290);
  
  return doc;
}

export function downloadPDF(container: ContainerData): void {
  const pdf = generatePDF(container);
  pdf.save(`Container_${container.containerNumber}_${new Date().toISOString().split('T')[0]}.pdf`);
}